### ISSUE TITLE
首屏闪烁的 bug

### ISSUE THREAD

**Issue by wuyudi** [shinnku-nikaidou/upset-gal-web#118]
一直有首屏闪烁的问题。偶然测试了下禁用脚本，发现页面停留在闪烁前。于是推测是 nextjs / antd 相关。
查 `next 首屏 css 跳变` 关键字得到

https://github.com/ant-design/ant-design/issues/16037

---

终于知道问题在哪了。

**Comment by shinnku-nikaidou** [comment]
这个我目前没有办法解决，我猜测是nextjs对antd水合不正确的原因

**Comment by shinnku-nikaidou** [comment]
已经解决了,🎉
