### ISSUE TITLE
文件夹下载偶尔有问题

### ISSUE THREAD

**Issue by wuyudi** [shinnku-nikaidou/upset-gal-web#85]
复现步骤：这里以 千恋万花 为例
1. 搜 “千”
2. ![image](https://user-images.githubusercontent.com/30024051/195174833-dcd5becb-e2f7-4904-9769-14818a4ff4c3.png) 点击。经多次测试是概率事件。
4. 有概率弹出报错 Application error: a client-side exception has occurred (see the browser console for more information)
5. 
![image](https://user-images.githubusercontent.com/30024051/195175229-2f6fc20b-12a1-4720-b656-5321c064354f.png)
---
另一个 end，正常显示。
![image](https://user-images.githubusercontent.com/30024051/195175424-5d6a40e3-d0ac-4197-af37-492ea1cae9e3.png)

**Comment by shinnku-nikaidou** [comment]
已修复。
