### ISSUE TITLE
关于电脑安装慢的问题解决方法与手机卡页面的问题解决

### ISSUE THREAD

**Issue by Azorse1985** [shinnku-nikaidou/upset-gal-web#96]
电脑安装慢或者无法安装的问题，可能会因人而异，我是无法用浏览器（Microsoft Edge）直接安装的，就算使用VPN也不行，需下载IDM（Internet Download Manager)插件方可安装,手机同理
手机卡页面的问题可能会发生，这个时候只能进入Github，只需挂后台一会就可以了，另外夸克封杀了这个网站

**Comment by shinnku-nikaidou** [comment]
被友商举报到国产浏览器黑名单没法解决，解决办法是别用这些阴间国产浏览器，还有我不懂什么是安装，网站所有内容都是直接下载
